### PR TITLE
AWS fix obtaining public IP address

### LINKED ISSUE #980: AWS assigning public IP address error
From time to time count of retries to get public IP address is not enough that leads to error

```
has finished with error aws: no public IP assigned
```

### PR DESCRIPTION
**Pull request by stgleb**
Use AWS SDK internal mechanism to wait until instance is running instead of
polling

Closes #980

### CODE REVIEW

**Comment by stgleb** [comment]
@saheienko Sure, but I am not sure if there is a guarantee that when instance is running it has public IP assigned

File: pkg/workflows/steps/amazon/create_machine.go [hunk 1]
```diff
@@ -182,50 +176,44 @@ func (s *StepCreateInstance) Run(ctx context.Context, w io.Writer, cfg *steps.Co
...
+		logrus.Debugf("Wait until instance %s running", nodeName)
+		err = EC2.WaitUntilInstanceRunningWithContext(ctx, lookup)
 
-			if len(out.Reservations) == 0 {
-				log.Infof("[%s] - found 0 ec2 instances, attempt %d", s.Name(), i)
-				time.Sleep(time.Duration(SleepSecondsPerAttempt) * time.Second)
-				continue
-			}
+		if err != nil {
+			logrus.Errorf("Error waiting instance running %v", err)
```
Comment (saheienko) [inline pkg/workflows/steps/amazon/create_machine.go]: Please, add instance/cluster name for this log to make it more informative.
