### PR TITLE
Fix race conditions in provisioner

### LINKED ISSUE #1349: Failed to provision cluster on AWS
**Short Summary:**
kube-apiserver endpoint not available on creating certificates step.

**Steps to Reproduce:**
Deploy a cluster with 1 master and 1 node.

**Expected Results:**
Cluster is ready

**Actual Results:**
```
NAME              STATUS     ROLES    AGE   VERSION
ip-10-2-116-126   Ready      master   32m   v1.13.5
ip-10-2-116-39    NotReady   <none>   27m   v1.13.5
```

**Dev Info:** (add links to log files)
1. Output of `go version`:
2. Commit hash or release tag used (`git log`): cfb1ac84dfacb08c8669b94da70cdd6ca7272020
3. Number of Masters and Nodes: 1/1
4. Cloud Provider: aws
5. Logs:
<details><summary>Logs</summary>
time="2019-04-01T19:03:42+03:00" level=info msg="[createMachine] - started"
time="2019-04-01T19:03:44+03:00" level=info msg="[aws_create_instance] - waiting to obtain public IP..."
time="2019-04-01T19:04:15+03:00" level=info msg="[aws_create_instance] - found public ip - 35.154.123.250 for node serhii-aws-node-07b3"
time="2019-04-01T19:04:15+03:00" level=info msg="[aws_create_instance] - success! Created node serhii-aws-node-07b3 with instanceID i-022ccea243ac68496 "
time="2019-04-01T19:04:15+03:00" level=info msg="[createMachine] - success"
time="2019-04-01T19:04:15+03:00" level=info msg="[ssh] - started"
time="2019-04-01T19:04:15+03:00" level=info msg="[ssh] - success"
time="2019-04-01T19:04:15+03:00" level=info msg="[add_authorized_keys] - started"
time="2019-04-01T19:04:15+03:00" level=info msg="[add_authorized_keys] - adding user's public key to the node"
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
time="2019-04-01T19:04:27+03:00" level=info msg="[add_authorized_keys] - success"
time="2019-04-01T19:04:27+03:00" level=info msg="[download_kubernetes_binary] - started"
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
time="2019-04-01T19:04:38+03:00" level=info msg="[download_kubernetes_binary] - success"
time="2019-04-01T19:04:38+03:00" level=info msg="[docker] - started"
sudo: unable to resolve host ip-10-2-116-39
--2019-04-01 16:04:39--  https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_18.06.3~ce~3-0~ubuntu_amd64.deb
Resolving download.docker.com (download.docker.com)... 13.35.202.94, 13.35.202.15, 13.35.202.27, ...
Connecting to download.docker.com (download.docker.com)|13.35.202.94|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40040990 (38M) [binary/octet-stream]
Saving to: ‘/tmp/docker-ce_18.06.3~ce~3-0~ubuntu_amd64.deb’

     0K .......... .......... .......... .......... ..........  0% 1.87M 20s
    50K .......... .......... .......... .......... ..........  0% 3.21M 16s
   100K .......... .......... .......... .......... ..........  0% 7.26M 12s
   150K .......... .......... .......... .......... ..........  0% 11.2M 10s
   200K .......... .......... .......... .......... ..........  0% 4.74M 10s
   250K .......... .......... .......... .......... ..........  0% 13.1M 9s
   300K .......... .......... .......... .......... ..........  0% 21.4M 8s
   350K .......... .......... .......... .......... ..........  1% 13.0M 7s
   400K .......... .......... .......... .......... ..........  1% 26.7M 6s
   450K .......... .......... .......... .......... ..........  1% 6.14M 6s
   500K .......... .......... .......... .......... ..........  1% 23.3M 6s
   550K .......... .......... .......... .......... ..........  1% 34.6M 6s
   600K .......... .......... .......... .......... ..........  1% 28.8M 5s
   650K .......... .......... .......... .......... ..........  1% 36.6M 5s
   700K .......... .......... .......... .......... ..........  1% 34.3M 5s
   750K .......... .......... .......... .......... ..........  2% 34.2M 4s
   800K .......... .......... .......... .......... ..........  2% 35.8M 4s
   850K .......... .......... .......... .......... ..........  2% 40.5M 4s
   900K .......... .......... .......... .......... ..........  2% 33.1M 4s
   950K .......... .......... .......... .......... ..........  2% 91.2M 4s
  1000K .......... .......... .......... .......... ..........  2% 6.94M 4s
  1050K .......... .......... .......... .......... ..........  2% 36.2M 4s
  1100K .......... .......... .......... .......... ..........  2% 40.2M 3s
  1150K .......... .......... .......... .......... ..........  3% 83.8M 3s
  1200K .......... .......... .......... .......... ..........  3% 56.7M 3s
  1250K .......... .......... .......... .......... ..........  3% 69.6M 3s
  1300K .......... .......... .......... .......... ..........  3% 57.1M 3s
  1350K .......... .......... .......... .......... ..........  3% 47.4M 3s
  1400K .......... .......... .......... .......... ..........  3%  136M 3s
  1450K .......... .......... .......... .......... ..........  3% 99.9M 3s
  1500K .......... .......... .......... .......... ..........  3% 59.9M 3s
  1550K .......... .......... .......... .......... ..........  4% 50.9M 3s
  1600K .......... .......... .......... .......... ..........  4% 81.5M 3s
  1650K .......... .......... .......... .......... ..........  4% 86.3M 3s
  1700K .......... .......... .......... .......... ..........  4%  120M 2s
  1750K .......... .......... .......... .......... ..........  4% 65.1M 2s
  1800K .......... .......... .......... .......... ..........  4% 89.8M 2s
  1850K .......... .......... .......... .......... ..........  4% 45.4M 2s
  1900K .......... .......... .......... .......... ..........  4% 89.7M 2s
  1950K .......... .......... .......... .......... ..........  5%  126M 2s
  2000K .......... .......... .......... .......... ..........  5% 8.60M 2s
  2050K .......... .......... .......... .......... ..........  5% 62.2M 2s
  2100K .......... .......... .......... .......... ..........  5% 41.5M 2s
  2150K .......... .......... .......... .......... ..........  5%  108M 2s
  2200K .......... .......... .......... .......... ..........  5%  126M 2s
  2250K .......... .......... .......... .......... ..........  5% 78.4M 2s
  2300K .......... .......... .......... .......... ..........  6% 80.9M 2s
  2350K .......... .......... .......... .......... ..........  6%  101M 2s
  2400K .......... .......... .......... .......... ..........  6%  102M 2s
  2450K .......... .......... .......... .......... ..........  6%  129M 2s
  2500K .......... .......... .......... .......... ..........  6%  111M 2s
  2550K .......... .......... .......... .......... ..........  6%  132M 2s
  2600K .......... .......... .......... .......... ..........  6%  104M 2s
  2650K .......... .......... .......... .......... ..........  6% 97.4M 2s
  2700K .......... .......... .......... .......... ..........  7% 98.4M 2s
  2750K .......... .......... .......... .......... ..........  7% 91.9M 2s
  2800K .......... .......... .......... .......... ..........  7%  127M 2s
  2850K .......... .......... .......... .......... ..........  7% 82.5M 2s
  2900K .......... .......... .......... .......... ..........  7%  128M 2s
  2950K .......... .......... .......... .......... ..........  7%  293M 2s
  3000K .......... .......... .......... .......... ..........  7%  108M 2s
  3050K .......... .......... .......... .......... ..........  7%  215M 2s
  3100K .......... .......... .......... .......... ..........  8%  256M 2s
  3150K .......... .......... .......... .......... ..........  8% 94.5M 2s
  3200K .......... .......... .......... .......... ..........  8% 69.6M 1s
  3250K .......... .......... .......... .......... ..........  8% 99.5M 1s
  3300K .......... .......... .......... .......... ..........  8% 76.1M 1s
  3350K .......... .......... .......... .......... ..........  8%  108M 1s
  3400K .......... .......... .......... .......... ..........  8% 48.7M 1s
  3450K .......... .......... .......... .......... ..........  8%  101M 1s
  3500K .......... .......... .......... .......... ..........  9% 7.85M 1s
  3550K .......... .......... .......... .......... ..........  9% 69.8M 1s
  3600K .......... .......... .......... .......... ..........  9%  226M 1s
  3650K .......... .......... .......... .......... ..........  9% 45.1M 1s
  3700K .......... .......... .......... .......... ..........  9% 92.7M 1s
  3750K .......... .......... .......... .......... ..........  9%  168M 1s
  3800K .......... .......... .......... .......... ..........  9%  116M 1s
  3850K .......... .......... .......... .......... ..........  9% 81.3M 1s
  3900K .......... .......... .......... .......... .......... 10% 82.0M 1s
  3950K .......... .......... .......... .......... .......... 10%  118M 1s
  4000K .......... .......... .......... .......... .......... 10% 97.3M 1s
  4050K .......... .......... .......... .......... .......... 10%  113M 1s
  4100K .......... .......... .......... .......... .......... 10%  169M 1s
  4150K .......... .......... .......... .......... .......... 10%  112M 1s
  4200K .......... .......... .......... .......... .......... 10% 95.9M 1s
  4250K .......... .......... .......... .......... .......... 10% 96.1M 1s
  4300K .......... .......... .......... .......... .......... 11% 85.4M 1s
  4350K .......... .......... .......... .......... .......... 11% 82.3M 1s
  4400K .......... .......... .......... .......... .......... 11%  181M 1s
  4450K .......... .......... .......... .......... .......... 11%  119M 1s
  4500K .......... .......... .......... .......... .......... 11%  123M 1s
  4550K .......... .......... .......... .......... .......... 11%  178M 1s
  4600K .......... .......... .......... .......... .......... 11%  238M 1s
  4650K .......... .......... .......... .......... .......... 12%  109M 1s
  4700K .......... .......... .......... .......... .......... 12%  102M 1s
  4750K .......... .......... .......... .......... .......... 12%  126M 1s
  4800K .......... .......... .......... .......... .......... 12% 64.3M 1s
  4850K .......... .......... .......... .......... .......... 12% 79.8M 1s
  4900K .......... .......... .......... .......... .......... 12%  171M 1s
  4950K .......... .......... .......... .......... .......... 12% 55.1M 1s
  5000K .......... .......... .......... .......... .......... 12% 73.1M 1s
  5050K .......... .......... .......... .......... .......... 13% 7.66M 1s
  5100K .......... .......... .......... .......... .......... 13%  112M 1s
  5150K .......... .......... .......... .......... .......... 13% 46.0M 1s
  5200K .......... .......... .......... .......... .......... 13% 94.3M 1s
  5250K .......... .......... .......... .......... .......... 13%  154M 1s
  5300K .......... .......... .......... .......... .......... 13%  101M 1s
  5350K .......... .......... .......... .......... .......... 13% 77.2M 1s
  5400K .......... .......... .......... .......... .......... 13% 93.1M 1s
  5450K .......... .......... .......... .......... .......... 14%  120M 1s
  5500K .......... .......... .......... .......... .......... 14%  168M 1s
  5550K .......... .......... .......... .......... .......... 14%  129M 1s
  5600K .......... .......... .......... .......... .......... 14%  100M 1s
  5650K .......... .......... .......... .......... .......... 14%  219M 1s
  5700K .......... .......... .......... .......... .......... 14% 99.0M 1s
  5750K .......... .......... .......... .......... .......... 14%  102M 1s
  5800K .......... .......... .......... .......... .......... 14% 93.6M 1s
  5850K .......... .......... .......... .......... .......... 15%  160M 1s
  5900K .......... .......... .......... .......... .......... 15%  142M 1s
  5950K .......... .......... .......... .......... .......... 15% 94.4M 1s
  6000K .......... .......... .......... .......... .......... 15%  111M 1s
  6050K .......... .......... .......... .......... .......... 15% 98.8M 1s
  6100K .......... .......... .......... .......... .......... 15%  129M 1s
  6150K .......... .......... .......... .......... .......... 15%  228M 1s
  6200K .......... .......... .......... .......... .......... 15% 92.2M 1s
  6250K .......... .......... .......... .......... .......... 16% 80.9M 1s
  6300K .......... .......... .......... .......... .......... 16% 76.1M 1s
  6350K .......... .......... .......... .......... .......... 16% 91.0M 1s
  6400K .......... .......... .......... .......... .......... 16%  119M 1s
  6450K .......... .......... .......... .......... .......... 16% 48.2M 1s
  6500K .......... .......... .......... .......... .......... 16% 82.3M 1s
  6550K .......... .......... .......... .......... .......... 16% 7.68M 1s
  6600K .......... .......... .......... .......... .......... 17%  110M 1s
  6650K .......... .......... .......... .......... .......... 17%  135M 1s
  6700K .......... .......... .......... .......... .......... 17% 52.7M 1s
  6750K .......... .......... .......... .......... .......... 17% 87.6M 1s
  6800K .......... .......... .......... .......... .......... 17% 87.3M 1s
  6850K .......... .......... .......... .......... .......... 17%  221M 1s
  6900K .......... .......... .......... .......... .......... 17% 58.4M 1s
  6950K .......... .......... .......... .......... .......... 17% 84.6M 1s
  7000K .......... .......... .......... .......... .......... 18%  113M 1s
  7050K .......... .......... .......... .......... .......... 18% 81.8M 1s
  7100K .......... .......... .......... .......... .......... 18%  143M 1s
  7150K .......... .......... .......... .......... .......... 18%  242M 1s
  7200K .......... .......... .......... .......... .......... 18% 86.6M 1s
  7250K .......... .......... .......... .......... .......... 18%  115M 1s
  7300K .......... .......... .......... .......... .......... 18%  122M 1s
  7350K .......... .......... .......... .......... .......... 18%  224M 1s
  7400K .......... .......... .......... .......... .......... 19% 95.6M 1s
  7450K .......... .......... .......... .......... .......... 19% 91.5M 1s
  7500K .......... .......... .......... .......... .......... 19% 96.4M 1s
  7550K .......... .......... .......... .......... .......... 19% 88.9M 1s
  7600K .......... .......... .......... .......... .......... 19%  150M 1s
  7650K .......... .......... .......... .......... .......... 19%  143M 1s
  7700K .......... .......... .......... .......... .......... 19%  155M 1s
  7750K .......... .......... .......... .......... .......... 19%  172M 1s
  7800K .......... .......... .......... .......... .......... 20%  121M 1s
  7850K .......... .......... .......... .......... .......... 20% 68.0M 1s
  7900K .......... .......... .......... .......... .......... 20% 89.5M 1s
  7950K .......... .......... .......... .......... .......... 20% 56.0M 1s
  8000K .......... .......... .......... .......... .......... 20%  133M 1s
  8050K .......... .......... .......... .......... .......... 20% 66.6M 1s
  8100K .......... .......... .......... .......... .......... 20% 7.79M 1s
  8150K .......... .......... .......... .......... .......... 20% 90.1M 1s
  8200K .......... .......... .......... .......... .......... 21% 55.6M 1s
  8250K .......... .......... .......... .......... .......... 21%  126M 1s
  8300K .......... .......... .......... .......... .......... 21% 98.9M 1s
  8350K .......... .......... .......... .......... .......... 21% 96.4M 1s
  8400K .......... .......... .......... .......... .......... 21% 72.5M 1s
  8450K .......... .......... .......... .......... .......... 21% 89.1M 1s
  8500K .......... .......... .......... .......... .......... 21%  153M 1s
  8550K .......... .......... .......... .......... .......... 21% 94.6M 1s
  8600K .......... .......... .......... .......... .......... 22%  107M 1s
  8650K .......... .......... .......... .......... .......... 22%  123M 1s
  8700K .......... .......... .......... .......... .......... 22%  203M 1s
  8750K .......... .......... .......... .......... .......... 22%  113M 1s
  8800K .......... .......... .......... .......... .......... 22%  109M 1s
  8850K .......... .......... .......... .......... .......... 22%  112M 1s
  8900K .......... .......... .......... .......... .......... 22%  116M 1s
  8950K .......... .......... .......... .......... .......... 23%  107M 1s
  9000K .......... .......... .......... .......... .......... 23% 87.9M 1s
  9050K .......... .......... .......... .......... .......... 23%  124M 1s
  9100K .......... .......... .......... .......... .......... 23%  105M 1s
  9150K .......... .......... .......... .......... .......... 23%  130M 1s
  9200K .......... .......... .......... .......... .......... 23%  105M 1s
  9250K .......... .......... .......... .......... .......... 23%  297M 1s
  9300K .......... .......... .......... .......... .......... 23% 89.1M 1s
  9350K .......... .......... .......... .......... .......... 24% 81.8M 1s
  9400K .......... .......... .......... .......... .......... 24% 78.4M 1s
  9450K .......... .......... .......... .......... .......... 24%  127M 1s
  9500K .......... .......... .......... .......... .......... 24% 46.8M 1s
  9550K .......... .......... .......... .......... .......... 24% 75.7M 1s
  9600K .......... .......... .......... .......... .......... 24% 8.34M 1s
  9650K .......... .......... .......... .......... .......... 24% 85.7M 1s
  9700K .......... .......... .......... .......... .......... 24%  102M 1s
  9750K .......... .......... .......... .......... .......... 25% 40.1M 1s
  9800K .......... .......... .......... .......... .......... 25% 82.3M 1s
  9850K .......... .......... .......... .......... .......... 25% 98.6M 1s
  9900K .......... .......... .......... .......... .......... 25%  228M 1s
  9950K .......... .......... .......... .......... .......... 25% 61.3M 1s
 10000K .......... .......... .......... .......... .......... 25%  111M 1s
 10050K .......... .......... .......... .......... .......... 25%  135M 1s
 10100K .......... .......... .......... .......... .......... 25%  137M 1s
 10150K .......... .......... .......... .......... .......... 26% 74.7M 1s
 10200K .......... .......... .......... .......... .......... 26%  145M 1s
 10250K .......... .......... .......... .......... .......... 26%  137M 1s
 10300K .......... .......... .......... .......... .......... 26%  144M 1s
 10350K .......... .......... .......... .......... .......... 26% 72.6M 1s
 10400K .......... .......... .......... .......... .......... 26%  270M 1s
 10450K .......... .......... .......... .......... .......... 26%  103M 1s
 10500K .......... .......... .......... .......... .......... 26%  136M 1s
 10550K .......... .......... .......... .......... .......... 27% 70.4M 1s
 10600K .......... .......... .......... .......... .......... 27% 92.8M 1s
 10650K .......... .......... .......... .......... .......... 27%  110M 1s
 10700K .......... .......... .......... .......... .......... 27%  118M 1s
 10750K .......... .......... .......... .......... .......... 27%  250M 1s
 10800K .......... .......... .......... .......... .......... 27%  138M 1s
 10850K .......... .......... .......... .......... .......... 27%  122M 1s
 10900K .......... .......... .......... .......... .......... 28% 88.3M 1s
 10950K .......... .......... .......... .......... .......... 28% 76.8M 1s
 11000K .......... .......... .......... .......... .......... 28% 54.8M 1s
 11050K .......... .......... .......... .......... .......... 28% 75.8M 1s
 11100K .......... .......... .......... .......... .......... 28%  115M 1s
 11150K .......... .......... .......... .......... .......... 28% 8.12M 1s
 11200K .......... .......... .......... .......... .......... 28% 89.9M 1s
 11250K .......... .......... .......... .......... .......... 28% 44.5M 1s
 11300K .......... .......... .......... .......... .......... 29%  130M 1s
 11350K .......... .......... .......... .......... .......... 29% 72.7M 1s
 11400K .......... .......... .......... .......... .......... 29%  128M 1s
 11450K .......... .......... .......... .......... .......... 29% 60.1M 1s
 11500K .......... .......... .......... .......... .......... 29% 89.0M 1s
 11550K .......... .......... .......... .......... .......... 29%  212M 1s
 11600K .......... .......... .......... .......... .......... 29% 74.9M 1s
 11650K .......... .......... .......... .......... .......... 29%  101M 1s
 11700K .......... .......... .......... .......... .......... 30%  102M 1s
 11750K .......... .......... .......... .......... .......... 30%  130M 1s
 11800K .......... .......... .......... .......... .......... 30%  128M 1s
 11850K .......... .......... .......... .......... .......... 30%  137M 1s
 11900K .......... .......... .......... .......... .......... 30%  143M 1s
 11950K .......... .......... .......... .......... .......... 30%  109M 1s
 12000K .......... .......... .......... .......... .......... 30%  222M 1s
 12050K .......... .......... .......... .......... .......... 30% 88.1M 1s
 12100K .......... .......... .......... .......... .......... 31% 86.8M 1s
 12150K .......... .......... .......... .......... .......... 31% 85.7M 1s
 12200K .......... .......... .......... .......... .......... 31%  186M 1s
 12250K .......... .......... .......... .......... .......... 31%  104M 1s
 12300K .......... .......... .......... .......... .......... 31%  272M 1s
 12350K .......... .......... .......... .......... .......... 31% 92.5M 1s
 12400K .......... .......... .......... .......... .......... 31%  106M 1s
 12450K .......... .......... .......... .......... .......... 31% 97.1M 1s
 12500K .......... .......... .......... .......... .......... 32%  117M 1s
 12550K .......... .......... .......... .......... .......... 32% 45.6M 1s
 12600K .......... .......... .......... .......... .......... 32% 74.7M 1s
 12650K .......... .......... .......... .......... .......... 32% 9.15M 1s
 12700K .......... .......... .......... .......... .......... 32% 41.4M 1s
 12750K .......... .......... .......... .......... .......... 32%  108M 1s
 12800K .......... .......... .......... .......... .......... 32% 44.6M 1s
 12850K .......... .......... .......... .......... .......... 32% 72.8M 1s
 12900K .......... .......... .......... .......... .......... 33%  103M 1s
 12950K .......... .......... .......... .......... .......... 33%  163M 1s
 13000K .......... .......... .......... .......... .......... 33% 52.7M 1s
 13050K .......... .......... .......... .......... .......... 33%  121M 1s
 13100K .......... .......... .......... .......... .......... 33%  110M 1s
 13150K .......... .......... .......... .......... .......... 33% 88.2M 1s
 13200K .......... .......... .......... .......... .......... 33% 97.6M 1s
 13250K .......... .......... .......... .......... .......... 34%  103M 1s
 13300K .......... .......... .......... .......... .......... 34%  242M 1s
 13350K .......... .......... .......... .......... .......... 34%  105M 1s
 13400K .......... .......... .......... .......... .......... 34%  101M 1s
 13450K .......... .......... .......... .......... .......... 34%  157M 1s
 13500K .......... .......... .......... .......... .......... 34%  141M 1s
 13550K .......... .......... .......... .......... .......... 34%  105M 1s
 13600K .......... .......... .......... .......... .......... 34%  102M 1s
 13650K .......... .......... .......... .......... .......... 35% 83.9M 1s
 13700K .......... .......... .......... .......... .......... 35%  141M 1s
 13750K .......... .......... .......... .......... .......... 35%  101M 1s
 13800K .......... .......... .......... .......... .......... 35%  280M 1s
 13850K .......... .......... .......... .......... .......... 35%  153M 1s
 13900K .......... .......... .......... .......... .......... 35%  120M 1s
 13950K .......... .......... .......... .......... .......... 35% 83.2M 1s
 14000K .......... .......... .......... .......... .......... 35% 87.2M 1s
 14050K .......... .......... .......... .......... .......... 36% 56.0M 1s
 14100K .......... .......... .......... .......... .......... 36%  130M 0s
 14150K .......... .......... .......... .......... .......... 36% 76.4M 0s
 14200K .......... .......... .......... .......... .......... 36% 8.36M 1s
 14250K .......... .......... .......... .......... .......... 36% 66.0M 1s
 14300K .......... .......... .......... .......... .......... 36% 42.7M 1s
 14350K .......... .......... .......... .......... .......... 36%  112M 1s
 14400K .......... .......... .......... .......... .......... 36% 72.6M 0s
 14450K .......... .......... .......... .......... .......... 37%  101M 0s
 14500K .......... .......... .......... .......... .......... 37% 81.9M 0s
 14550K .......... .......... .......... .......... .......... 37%  101M 0s
 14600K .......... .......... .......... .......... .......... 37%  122M 0s
 14650K .......... .......... .......... .......... .......... 37% 79.8M 0s
 14700K .......... .......... .......... .......... .......... 37%  115M 0s
 14750K .......... .......... .......... .......... .......... 37% 95.7M 0s
 14800K .......... .......... .......... .......... .......... 37%  104M 0s
 14850K .......... .......... .......... .......... .......... 38%  242M 0s
 14900K .......... .......... .......... .......... .......... 38% 95.4M 0s
 14950K .......... .......... .......... .......... .......... 38%  118M 0s
 15000K .......... .......... .......... .......... .......... 38%  118M 0s
 15050K .......... .......... .......... .......... .......... 38%  155M 0s
 15100K .......... .......... .......... .......... .......... 38%  110M 0s
 15150K .......... .......... .......... .......... .......... 38% 92.5M 0s
 15200K .......... .......... .......... .......... .......... 39% 89.2M 0s
 15250K .......... .......... .......... .......... .......... 39%  109M 0s
 15300K .......... .......... .......... .......... .......... 39%  137M 0s
 15350K .......... .......... .......... .......... .......... 39%  254M 0s
 15400K .......... .......... .......... .......... .......... 39%  119M 0s
 15450K .......... .......... .......... .......... .......... 39% 87.6M 0s
 15500K .......... .......... .......... .......... .......... 39%  102M 0s
 15550K .......... .......... .......... .......... .......... 39%  106M 0s
 15600K .......... .......... .......... .......... .......... 40% 49.6M 0s
 15650K .......... .......... .......... .......... .......... 40% 82.0M 0s
 15700K .......... .......... .......... .......... .......... 40% 10.3M 0s
 15750K .......... .......... .......... .......... .......... 40% 27.7M 0s
 15800K .......... .......... .......... .......... .......... 40%  129M 0s
 15850K .......... .......... .......... .......... .......... 40% 38.3M 0s
 15900K .......... .......... .......... .......... .......... 40% 95.6M 0s
 15950K .......... .......... .......... .......... .......... 40% 91.2M 0s
 16000K .......... .......... .......... .......... .......... 41%  135M 0s
 16050K .......... .......... .......... .......... .......... 41% 62.9M 0s
 16100K .......... .......... .......... .......... .......... 41%  122M 0s
 16150K .......... .......... .......... .......... .......... 41% 81.4M 0s
 16200K .......... .......... .......... .......... .......... 41% 89.6M 0s
 16250K .......... .......... .......... .......... .......... 41%  252M 0s
 16300K .......... .......... .......... .......... .......... 41% 86.7M 0s
 16350K .......... .......... .......... .......... .......... 41%  115M 0s
 16400K .......... .......... .......... .......... .......... 42%  114M 0s
 16450K .......... .......... .......... .......... .......... 42% 96.3M 0s
 16500K .......... .......... .......... .......... .......... 42%  206M 0s
 16550K .......... .......... .......... .......... .......... 42%  103M 0s
 16600K .......... .......... .......... .......... .......... 42%  109M 0s
 16650K .......... .......... .......... .......... .......... 42% 86.7M 0s
 16700K .......... .......... .......... .......... .......... 42%  114M 0s
 16750K .......... .......... .......... .......... .......... 42% 75.9M 0s
 16800K .......... .......... .......... .......... .......... 43%  141M 0s
 16850K .......... .......... .......... .......... .......... 43%  270M 0s
 16900K .......... .......... .......... .......... .......... 43% 96.2M 0s
 16950K .......... .......... .......... .......... .......... 43%  138M 0s
 17000K .......... .......... .......... .......... .......... 43%  110M 0s
 17050K .......... .......... .......... .......... .......... 43%  101M 0s
 17100K .......... .......... .......... .......... .......... 43% 61.1M 0s
 17150K .......... .......... .......... .......... .......... 43% 74.9M 0s
 17200K .......... .......... .......... .......... .......... 44%  127M 0s
 17250K .......... .......... .......... .......... .......... 44% 8.75M 0s
 17300K .......... .......... .......... .......... .......... 44% 48.8M 0s
 17350K .......... .......... .......... .......... .......... 44% 45.4M 0s
 17400K .......... .......... .......... .......... .......... 44%  114M 0s
 17450K .......... .......... .......... .......... .......... 44% 62.1M 0s
 17500K .......... .......... .......... .......... .......... 44% 98.6M 0s
 17550K .......... .......... .......... .......... .......... 45% 69.7M 0s
 17600K .......... .......... .......... .......... .......... 45%  112M 0s
 17650K .......... .......... .......... .......... .......... 45%  107M 0s
 17700K .......... .......... .......... .......... .......... 45%  142M 0s
 17750K .......... .......... .......... .......... .......... 45%  101M 0s
 17800K .......... .......... .......... .......... .......... 45% 99.8M 0s
 17850K .......... .......... .......... .......... .......... 45%  173M 0s
 17900K .......... .......... .......... .......... .......... 45%  139M 0s
 17950K .......... .......... .......... .......... .......... 46% 71.0M 0s
 18000K .......... .......... .......... .......... .......... 46%  117M 0s
 18050K .......... .......... .......... .......... .......... 46%  118M 0s
 18100K .......... .......... .......... .......... .......... 46%  141M 0s
 18150K .......... .......... .......... .......... .......... 46%  103M 0s
 18200K .......... .......... .......... .......... .......... 46%  109M 0s
 18250K .......... .......... .......... .......... .......... 46%  105M 0s
 18300K .......... .......... .......... .......... .......... 46% 62.6M 0s
 18350K .......... .......... .......... .......... .......... 47%  252M 0s
 18400K .......... .......... .......... .......... .......... 47%  106M 0s
 18450K .......... .......... .......... .......... .......... 47%  289M 0s
 18500K .......... .......... .......... .......... .......... 47%  102M 0s
 18550K .......... .......... .......... .......... .......... 47%  107M 0s
 18600K .......... .......... .......... .......... .......... 47%  121M 0s
 18650K .......... .......... .......... .......... .......... 47% 52.9M 0s
 18700K .......... .......... .......... .......... .......... 47% 71.2M 0s
 18750K .......... .......... .......... .......... .......... 48% 9.18M 0s
 18800K .......... .......... .......... .......... .......... 48% 49.6M 0s
 18850K .......... .......... .......... .......... .......... 48%  116M 0s
 18900K .......... .......... .......... .......... .......... 48% 35.5M 0s
 18950K .......... .......... .......... .......... .......... 48% 91.6M 0s
 19000K .......... .......... .......... .......... .......... 48% 96.5M 0s
 19050K .......... .......... .......... .......... .......... 48%  123M 0s
 19100K .......... .......... .......... .......... .......... 48% 59.9M 0s
 19150K .......... .......... .......... .......... .......... 49% 81.9M 0s
 19200K .......... .......... .......... .......... .......... 49%  111M 0s
 19250K .......... .......... .......... .......... .......... 49%  126M 0s
 19300K .......... .......... .......... .......... .......... 49%  108M 0s
 19350K .......... .......... .......... .......... .......... 49%  125M 0s
 19400K .......... .......... .......... .......... .......... 49%  116M 0s
 19450K .......... .......... .......... .......... .......... 49%  117M 0s
 19500K .......... .......... .......... .......... .......... 49% 76.9M 0s
 19550K .......... .......... .......... .......... .......... 50%  142M 0s
 19600K .......... .......... .......... .......... .......... 50%  154M 0s
 19650K .......... .......... .......... .......... .......... 50%  116M 0s
 19700K .......... .......... .......... .......... .......... 50% 88.3M 0s
 19750K .......... .......... .......... .......... .......... 50%  119M 0s
 19800K .......... .......... .......... .......... .......... 50%  153M 0s
 19850K .......... .......... .......... .......... .......... 50% 93.0M 0s
 19900K .......... .......... .......... .......... .......... 51%  161M 0s
 19950K .......... .......... .......... .......... .......... 51%  102M 0s
 20000K .......... .......... .......... .......... .......... 51%  288M 0s
 20050K .......... .......... .......... .......... .......... 51% 94.3M 0s
 20100K .......... .......... .......... .......... .......... 51% 79.0M 0s
 20150K .......... .......... .......... .......... .......... 51% 63.2M 0s
 20200K .......... .......... .......... .......... .......... 51% 75.4M 0s
 20250K .......... .......... .......... .......... .......... 51%  116M 0s
 20300K .......... .......... .......... .......... .......... 52% 9.10M 0s
 20350K .......... .......... .......... .......... .......... 52% 41.3M 0s
 20400K .......... .......... .......... .......... .......... 52% 37.9M 0s
 20450K .......... .......... .......... .......... .......... 52% 98.4M 0s
 20500K .......... .......... .......... .......... .......... 52%  114M 0s
 20550K .......... .......... .......... .......... .......... 52% 85.6M 0s
 20600K .......... .......... .......... .......... .......... 52% 76.5M 0s
 20650K .......... .......... .......... .......... .......... 52%  142M 0s
 20700K .......... .......... .......... .......... .......... 53% 76.2M 0s
 20750K .......... .......... .......... .......... .......... 53%  116M 0s
 20800K .......... .......... .......... .......... .......... 53%  101M 0s
 20850K .......... .......... .......... .......... .......... 53%  102M 0s
 20900K .......... .......... .......... .......... .......... 53% 99.1M 0s
 20950K .......... .......... .......... .......... .......... 53%  290M 0s
 21000K .......... .......... .......... .......... .......... 53% 80.0M 0s
 21050K .......... .......... .......... .......... .......... 53%  106M 0s
 21100K .......... .......... .......... .......... .......... 54% 97.3M 0s
 21150K .......... .......... .......... .......... .......... 54%  130M 0s
 21200K .......... .......... .......... .......... .......... 54%  107M 0s
 21250K .......... .......... .......... .......... .......... 54%  135M 0s
 21300K .......... .......... .......... .......... .......... 54% 88.0M 0s
 21350K .......... .......... .......... .......... .......... 54%  126M 0s
 21400K .......... .......... .......... .......... .......... 54%  121M 0s
 21450K .......... .......... .......... .......... .......... 54% 87.0M 0s
 21500K .......... .......... .......... .......... .......... 55%  130M 0s
 21550K .......... .......... .......... .......... .......... 55%  107M 0s
 21600K .......... .......... .......... .......... .......... 55%  165M 0s
 21650K .......... .......... .......... .......... .......... 55% 60.8M 0s
 21700K .......... .......... .......... .......... .......... 55%  151M 0s
 21750K .......... .......... .......... .......... .......... 55% 85.4M 0s
 21800K .......... .......... .......... .......... .......... 55% 8.76M 0s
 21850K .......... .......... .......... .......... .......... 56% 53.9M 0s
 21900K .......... .......... .......... .......... .......... 56%  114M 0s
 21950K .......... .......... .......... .......... .......... 56% 33.3M 0s
 22000K .......... .......... .......... .......... .......... 56% 77.2M 0s
 22050K .......... .......... .......... .......... .......... 56%  113M 0s
 22100K .......... .......... .......... .......... .......... 56%  126M 0s
 22150K .......... .......... .......... .......... .......... 56% 77.7M 0s
 22200K .......... .......... .......... .......... .......... 56% 73.7M 0s
 22250K .......... .......... .......... .......... .......... 57%  122M 0s
 22300K .......... .......... .......... .......... .......... 57%  133M 0s
 22350K .......... .......... .......... .......... .......... 57% 80.8M 0s
 22400K .......... .......... .......... .......... .......... 57%  104M 0s
 22450K .......... .......... .......... .......... .......... 57%  152M 0s
 22500K .......... .......... .......... .......... .......... 57%  103M 0s
 22550K .......... .......... .......... .......... .......... 57% 87.2M 0s
 22600K .......... .......... .......... .......... .......... 57% 93.3M 0s
 22650K .......... .......... .......... .......... .......... 58%  299M 0s
 22700K .......... .......... .......... .......... .......... 58%  101M 0s
 22750K .......... .......... .......... .......... .......... 58% 91.0M 0s
 22800K .......... .......... .......... .......... .......... 58%  163M 0s
 22850K .......... .......... .......... .......... .......... 58% 95.8M 0s
 22900K .......... .......... .......... .......... .......... 58%  142M 0s
 22950K .......... .......... .......... .......... .......... 58%  117M 0s
 23000K .......... .......... .......... .......... .......... 58% 93.6M 0s
 23050K .......... .......... .......... .......... .......... 59% 80.0M 0s
 23100K .......... .......... .......... .......... .......... 59%  221M 0s
 23150K .......... .......... .......... .......... .......... 59% 98.7M 0s
 23200K .......... .......... .......... .......... .......... 59%  144M 0s
 23250K .......... .......... .......... .......... .......... 59% 62.1M 0s
 23300K .......... .......... .......... .......... .......... 59%  117M 0s
 23350K .......... .......... .......... .......... .......... 59% 8.94M 0s
 23400K .......... .......... .......... .......... .......... 59% 45.0M 0s
 23450K .......... .......... .......... .......... .......... 60% 34.1M 0s
 23500K .......... .......... .......... .......... .......... 60%  104M 0s
 23550K .......... .......... .......... .......... .......... 60%  107M 0s
 23600K .......... .......... .......... .......... .......... 60% 88.0M 0s
 23650K .......... .......... .......... .......... .......... 60% 71.5M 0s
 23700K .......... .......... .......... .......... .......... 60% 87.3M 0s
 23750K .......... .......... .......... .......... .......... 60%  101M 0s
 23800K .......... .......... .......... .......... .......... 60%  106M 0s
 23850K .......... .......... .......... .......... .......... 61%  101M 0s
 23900K .......... .......... .......... .......... .......... 61% 89.0M 0s
 23950K .......... .......... .......... .......... .......... 61%  119M 0s
 24000K .......... .......... .......... .......... .......... 61%  299M 0s
 24050K .......... .......... .......... .......... .......... 61% 82.3M 0s
 24100K .......... .......... .......... .......... .......... 61% 75.1M 0s
 24150K .......... .......... .......... .......... .......... 61%  202M 0s
 24200K .......... .......... .......... .......... .......... 62%  161M 0s
 24250K .......... .......... .......... .......... .......... 62% 78.9M 0s
 24300K .......... .......... .......... .......... .......... 62%  173M 0s
 24350K .......... .......... .......... .......... .......... 62%  124M 0s
 24400K .......... .......... .......... .......... .......... 62%  101M 0s
 24450K .......... .......... .......... .......... .......... 62%  125M 0s
 24500K .......... .......... .......... .......... .......... 62%  119M 0s
 24550K .......... .......... .......... .......... .......... 62% 79.0M 0s
 24600K .......... .......... .......... .......... .......... 63% 90.1M 0s
 24650K .......... .......... .......... .......... .......... 63%  124M 0s
 24700K .......... .......... .......... .......... .......... 63%  303M 0s
 24750K .......... .......... .......... .......... .......... 63% 83.3M 0s
 24800K .......... .......... .......... .......... .......... 63% 78.2M 0s
 24850K .......... .......... .......... .......... .......... 63% 8.51M 0s
 24900K .......... .......... .......... .......... .......... 63% 55.5M 0s
 24950K .......... .......... .......... .......... .......... 63%  127M 0s
 25000K .......... .......... .......... .......... .......... 64% 41.2M 0s
 25050K .......... .......... .......... .......... .......... 64% 59.9M 0s
 25100K .......... .......... .......... .......... .......... 64%  101M 0s
 25150K .......... .......... .......... .......... .......... 64%  134M 0s
 25200K .......... .......... .......... .......... .......... 64% 69.4M 0s
 25250K .......... .......... .......... .......... .......... 64% 70.2M 0s
 25300K .......... .......... .......... .......... .......... 64%  106M 0s
 25350K .......... .......... .......... .......... .......... 64%  115M 0s
 25400K .......... .......... .......... .......... .......... 65% 92.5M 0s
 25450K .......... .......... .......... .......... .......... 65% 74.8M 0s
 25500K .......... .......... .......... .......... .......... 65%  280M 0s
 25550K .......... .......... .......... .......... .......... 65%  132M 0s
 25600K .......... .......... .......... .......... .......... 65% 92.8M 0s
 25650K .......... .......... .......... .......... .......... 65% 84.8M 0s
 25700K .......... .......... .......... .......... .......... 65%  280M 0s
 25750K .......... .......... .......... .......... .......... 65%  116M 0s
 25800K .......... .......... .......... .......... .......... 66% 88.0M 0s
 25850K .......... .......... .......... .......... .......... 66%  166M 0s
 25900K .......... .......... .......... .......... .......... 66% 98.1M 0s
 25950K .......... .......... .......... .......... .......... 66%  135M 0s
 26000K .......... .......... .......... .......... .......... 66% 86.8M 0s
 26050K .......... .......... .......... .......... .......... 66%  105M 0s
 26100K .......... .......... .......... .......... .......... 66%  122M 0s
 26150K .......... .......... .......... .......... .......... 67%  108M 0s
 26200K .......... .......... .......... .......... .......... 67%  128M 0s
 26250K .......... .......... .......... .......... .......... 67%  103M 0s
 26300K .......... .......... .......... .......... .......... 67% 73.0M 0s
 26350K .......... .......... .......... .......... .......... 67%  123M 0s
 26400K .......... .......... .......... .......... .......... 67% 8.63M 0s
 26450K .......... .......... .......... .......... .......... 67% 43.9M 0s
 26500K .......... .......... .......... .......... .......... 67% 58.3M 0s
 26550K .......... .......... .......... .......... .......... 68% 56.1M 0s
 26600K .......... .......... .......... .......... .......... 68%  125M 0s
 26650K .......... .......... .......... .......... .......... 68% 86.5M 0s
 26700K .......... .......... .......... .......... .......... 68% 76.2M 0s
 26750K .......... .......... .......... .......... .......... 68% 65.6M 0s
 26800K .......... .......... .......... .......... .......... 68%  131M 0s
 26850K .......... .......... .......... .......... .......... 68%  109M 0s
 26900K .......... .......... .......... .......... .......... 68% 75.7M 0s
 26950K .......... .......... .......... .......... .......... 69% 74.8M 0s
 27000K .......... .......... .......... .......... .......... 69%  176M 0s
 27050K .......... .......... .......... .......... .......... 69%  187M 0s
 27100K .......... .......... .......... .......... .......... 69% 83.2M 0s
 27150K .......... .......... .......... .......... .......... 69%  145M 0s
 27200K .......... .......... .......... .......... .......... 69%  116M 0s
 27250K .......... .......... .......... .......... .......... 69%  164M 0s
 27300K .......... .......... .......... .......... .......... 69% 94.1M 0s
 27350K .......... .......... .......... .......... .......... 70%  158M 0s
 27400K .......... .......... .......... .......... .......... 70%  117M 0s
 27450K .......... .......... .......... .......... .......... 70% 94.2M 0s
 27500K .......... .......... .......... .......... .......... 70%  189M 0s
 27550K .......... .......... .......... .......... .......... 70%  127M 0s
 27600K .......... .......... .......... .......... .......... 70% 75.7M 0s
 27650K .......... .......... .......... .......... .......... 70%  126M 0s
 27700K .......... .......... .......... .......... .......... 70%  118M 0s
 27750K .......... .......... .......... .......... .......... 71%  167M 0s
 27800K .......... .......... .......... .......... .......... 71% 75.2M 0s
 27850K .......... .......... .......... .......... .......... 71% 57.8M 0s
 27900K .......... .......... .......... .......... .......... 71% 8.94M 0s
 27950K .......... .......... .......... .......... .......... 71% 76.3M 0s
 28000K .......... .......... .......... .......... .......... 71% 33.8M 0s
 28050K .......... .......... .......... .......... .......... 71%  109M 0s
 28100K .......... .......... .......... .......... .......... 71% 63.3M 0s
 28150K .......... .......... .......... .......... .......... 72%  101M 0s
 28200K .......... .......... .......... .......... .......... 72% 78.3M 0s
 28250K .......... .......... .......... .......... .......... 72%  111M 0s
 28300K .......... .......... .......... .......... .......... 72% 59.8M 0s
 28350K .......... .......... .......... .......... .......... 72%  146M 0s
 28400K .......... .......... .......... .......... .......... 72% 81.5M 0s
 28450K .......... .......... .......... .......... .......... 72%  122M 0s
 28500K .......... .......... .......... .......... .......... 73% 83.4M 0s
 28550K .......... .......... .......... .......... .......... 73%  184M 0s
 28600K .......... .......... .......... .......... .......... 73%  125M 0s
 28650K .......... .......... .......... .......... .......... 73%  128M 0s
 28700K .......... .......... .......... .......... .......... 73% 85.8M 0s
 28750K .......... .......... .......... .......... .......... 73%  167M 0s
 28800K .......... .......... .......... .......... .......... 73% 96.3M 0s
 28850K .......... .......... .......... .......... .......... 73%  123M 0s
 28900K .......... .......... .......... .......... .......... 74%  123M 0s
 28950K .......... .......... .......... .......... .......... 74%  153M 0s
 29000K .......... .......... .......... .......... .......... 74% 99.7M 0s
 29050K .......... .......... .......... .......... .......... 74%  161M 0s
 29100K .......... .......... .......... .......... .......... 74% 84.7M 0s
 29150K .......... .......... .......... .......... .......... 74%  114M 0s
 29200K .......... .......... .......... .......... .......... 74%  106M 0s
 29250K .......... .......... .......... .......... .......... 74%  133M 0s
 29300K .......... .......... .......... .......... .......... 75% 92.2M 0s
 29350K .......... .......... .......... .......... .......... 75% 64.0M 0s
 29400K .......... .......... .......... .......... .......... 75%  128M 0s
 29450K .......... .......... .......... .......... .......... 75% 8.62M 0s
 29500K .......... .......... .......... .......... .......... 75% 63.7M 0s
 29550K .......... .......... .......... .......... .......... 75% 44.5M 0s
 29600K .......... .......... .......... .......... .......... 75% 56.5M 0s
 29650K .......... .......... .......... .......... .......... 75%  127M 0s
 29700K .......... .......... .......... .......... .......... 76% 76.5M 0s
 29750K .......... .......... .......... .......... .......... 76% 81.8M 0s
 29800K .......... .......... .......... .......... .......... 76% 63.2M 0s
 29850K .......... .......... .......... .......... .......... 76%  119M 0s
 29900K .......... .......... .......... .......... .......... 76%  109M 0s
 29950K .......... .......... .......... .......... .......... 76% 88.2M 0s
 30000K .......... .......... .......... .......... .......... 76% 87.1M 0s
 30050K .......... .......... .......... .......... .......... 76%  107M 0s
 30100K .......... .......... .......... .......... .......... 77%  205M 0s
 30150K .......... .......... .......... .......... .......... 77%  128M 0s
 30200K .......... .......... .......... .......... .......... 77% 86.9M 0s
 30250K .......... .......... .......... .......... .......... 77%  111M 0s
 30300K .......... .......... .......... .......... .......... 77%  153M 0s
 30350K .......... .......... .......... .......... .......... 77% 85.1M 0s
 30400K .......... .......... .......... .......... .......... 77%  197M 0s
 30450K .......... .......... .......... .......... .......... 78% 89.0M 0s
 30500K .......... .......... .......... .......... .......... 78%  120M 0s
 30550K .......... .......... .......... .......... .......... 78%  138M 0s
 30600K .......... .......... .......... .......... .......... 78%  131M 0s
 30650K .......... .......... .......... .......... .......... 78% 89.2M 0s
 30700K .......... .......... .......... .......... .......... 78%  121M 0s
 30750K .......... .......... .......... .......... .......... 78% 83.0M 0s
 30800K .......... .......... .......... .......... .......... 78%  171M 0s
 30850K .......... .......... .......... .......... .......... 79%  127M 0s
 30900K .......... .......... .......... .......... .......... 79% 59.1M 0s
 30950K .......... .......... .......... .......... .......... 79% 8.95M 0s
 31000K .......... .......... .......... .......... .......... 79% 59.3M 0s
 31050K .......... .......... .......... .......... .......... 79%  122M 0s
 31100K .......... .......... .......... .......... .......... 79% 41.6M 0s
 31150K .......... .......... .......... .......... .......... 79% 54.8M 0s
 31200K .......... .......... .......... .......... .......... 79% 93.7M 0s
 31250K .......... .......... .......... .......... .......... 80% 71.6M 0s
 31300K .......... .......... .......... .......... .......... 80%  120M 0s
 31350K .......... .......... .......... .......... .......... 80% 73.0M 0s
 31400K .......... .......... .......... .......... .......... 80% 95.1M 0s
 31450K .......... .......... .......... .......... .......... 80% 94.4M 0s
 31500K .......... .......... .......... .......... .......... 80%  153M 0s
 31550K .......... .......... .......... .......... .......... 80% 92.1M 0s
 31600K .......... .......... .......... .......... .......... 80%  110M 0s
 31650K .......... .......... .......... .......... .......... 81%  135M 0s
 31700K .......... .......... .......... .......... .......... 81% 97.7M 0s
 31750K .......... .......... .......... .......... .......... 81% 82.4M 0s
 31800K .......... .......... .......... .......... .......... 81%  171M 0s
 31850K .......... .......... .......... .......... .......... 81%  118M 0s
 31900K .......... .......... .......... .......... .......... 81%  119M 0s
 31950K .......... .......... .......... .......... .......... 81%  130M 0s
 32000K .......... .......... .......... .......... .......... 81%  147M 0s
 32050K .......... .......... .......... .......... .......... 82% 90.9M 0s
 32100K .......... .......... .......... .......... .......... 82% 88.3M 0s
 32150K .......... .......... .......... .......... .......... 82%  127M 0s
 32200K .......... .......... .......... .......... .......... 82%  121M 0s
 32250K .......... .......... .......... .......... .......... 82% 88.1M 0s
 32300K .......... .......... .......... .......... .......... 82%  148M 0s
 32350K .......... .......... .......... .......... .......... 82%  125M 0s
 32400K .......... .......... .......... .......... .......... 82% 61.9M 0s
 32450K .......... .......... .......... .......... .......... 83% 9.90M 0s
 32500K .......... .......... .......... .......... .......... 83% 67.4M 0s
 32550K .......... .......... .......... .......... .......... 83% 46.6M 0s
 32600K .......... .......... .......... .......... .......... 83% 42.1M 0s
 32650K .......... .......... .......... .......... .......... 83% 56.3M 0s
 32700K .......... .......... .......... .......... .......... 83%  129M 0s
 32750K .......... .......... .......... .......... .......... 83% 94.3M 0s
 32800K .......... .......... .......... .......... .......... 84% 76.0M 0s
 32850K .......... .......... .......... .......... .......... 84% 53.2M 0s
 32900K .......... .......... .......... .......... .......... 84%  120M 0s
 32950K .......... .......... .......... .......... .......... 84%  127M 0s
 33000K .......... .......... .......... .......... .......... 84% 75.9M 0s
 33050K .......... .......... .......... .......... .......... 84%  124M 0s
 33100K .......... .......... .......... .......... .......... 84%  102M 0s
 33150K .......... .......... .......... .......... .......... 84%  142M 0s
 33200K .......... .......... .......... .......... .......... 85%  113M 0s
 33250K .......... .......... .......... .......... .......... 85%  114M 0s
 33300K .......... .......... .......... .......... .......... 85%  108M 0s
 33350K .......... .......... .......... .......... .......... 85%  131M 0s
 33400K .......... .......... .......... .......... .......... 85% 89.7M 0s
 33450K .......... .......... .......... .......... .......... 85%  106M 0s
 33500K .......... .......... .......... .......... .......... 85%  136M 0s
 33550K .......... .......... .......... .......... .......... 85%  136M 0s
 33600K .......... .......... .......... .......... .......... 86%  140M 0s
 33650K .......... .......... .......... .......... .......... 86%  114M 0s
 33700K .......... .......... .......... .......... .......... 86% 86.0M 0s
 33750K .......... .......... .......... .......... .......... 86%  116M 0s
 33800K .......... .......... .......... .......... .......... 86% 92.8M 0s
 33850K .......... .......... .......... .......... .......... 86% 96.0M 0s
 33900K .......... .......... .......... .......... .......... 86%  236M 0s
 33950K .......... .......... .......... .......... .......... 86% 59.5M 0s
 34000K .......... .......... .......... .......... .......... 87% 9.72M 0s
 34050K .......... .......... .......... .......... .......... 87% 38.9M 0s
 34100K .......... .......... .......... .......... .......... 87%  109M 0s
 34150K .......... .......... .......... .......... .......... 87% 43.1M 0s
 34200K .......... .......... .......... .......... .......... 87% 49.9M 0s
 34250K .......... .......... .......... .......... .......... 87%  141M 0s
 34300K .......... .......... .......... .......... .......... 87% 70.8M 0s
 34350K .......... .......... .......... .......... .......... 87%  119M 0s
 34400K .......... .......... .......... .......... .......... 88% 69.7M 0s
 34450K .......... .......... .......... .......... .......... 88% 82.6M 0s
 34500K .......... .......... .......... .......... .......... 88% 89.0M 0s
 34550K .......... .......... .......... .......... .......... 88%  111M 0s
 34600K .......... .......... .......... .......... .......... 88% 79.4M 0s
 34650K .......... .......... .......... .......... .......... 88%  124M 0s
 34700K .......... .......... .......... .......... .......... 88%  126M 0s
 34750K .......... .......... .......... .......... .......... 88% 99.9M 0s
 34800K .......... .......... .......... .......... .......... 89%  108M 0s
 34850K .......... .......... .......... .......... .......... 89%  278M 0s
 34900K .......... .......... .......... .......... .......... 89% 87.3M 0s
 34950K .......... .......... .......... .......... .......... 89%  127M 0s
 35000K .......... .......... .......... .......... .......... 89%  136M 0s
 35050K .......... .......... .......... .......... .......... 89%  148M 0s
 35100K .......... .......... .......... .......... .......... 89%  103M 0s
 35150K .......... .......... .......... .......... .......... 90%  116M 0s
 35200K .......... .......... .......... .......... .......... 90% 97.6M 0s
 35250K .......... .......... .......... .......... .......... 90% 93.0M 0s
 35300K .......... .......... .......... .......... .......... 90% 93.5M 0s
 35350K .......... .......... .......... .......... .......... 90%  107M 0s
 35400K .......... .......... .......... .......... .......... 90%  133M 0s
 35450K .......... .......... .......... .......... .......... 90% 74.8M 0s
 35500K .......... .......... .......... .......... .......... 90%  146M 0s
 35550K .......... .......... .......... .......... .......... 91% 9.94M 0s
 35600K .......... .......... .......... .......... .......... 91% 30.2M 0s
 35650K .......... .......... .......... .......... .......... 91% 48.3M 0s
 35700K .......... .......... .......... .......... .......... 91% 65.2M 0s
 35750K .......... .......... .......... .......... .......... 91%  116M 0s
 35800K .......... .......... .......... .......... .......... 91% 84.5M 0s
 35850K .......... .......... .......... .......... .......... 91% 69.7M 0s
 35900K .......... .......... .......... .......... .......... 91% 91.9M 0s
 35950K .......... .......... .......... .......... .......... 92% 88.4M 0s
 36000K .......... .......... .......... .......... .......... 92%  131M 0s
 36050K .......... .......... .......... .......... .......... 92% 63.3M 0s
 36100K .......... .......... .......... .......... .......... 92% 97.2M 0s
 36150K .......... .......... .......... .......... .......... 92%  112M 0s
 36200K .......... .......... .......... .......... .......... 92%  152M 0s
 36250K .......... .......... .......... .......... .......... 92%  127M 0s
 36300K .......... .......... .......... .......... .......... 92% 95.5M 0s
 36350K .......... .......... .......... .......... .......... 93% 99.6M 0s
 36400K .......... .......... .......... .......... .......... 93%  105M 0s
 36450K .......... .......... .......... .......... .......... 93%  104M 0s
 36500K .......... .......... .......... .......... .......... 93%  192M 0s
 36550K .......... .......... .......... .......... .......... 93%  113M 0s
 36600K .......... .......... .......... .......... .......... 93%  176M 0s
 36650K .......... .......... .......... .......... .......... 93%  148M 0s
 36700K .......... .......... .......... .......... .......... 93% 58.0M 0s
 36750K .......... .......... .......... .......... .......... 94%  137M 0s
 36800K .......... .......... .......... .......... .......... 94%  104M 0s
 36850K .......... .......... .......... .......... .......... 94%  114M 0s
 36900K .......... .......... .......... .......... .......... 94% 89.5M 0s
 36950K .......... .......... .......... .......... .......... 94%  195M 0s
 37000K .......... .......... .......... .......... .......... 94% 73.3M 0s
 37050K .......... .......... .......... .......... .......... 94% 10.5M 0s
 37100K .......... .......... .......... .......... .......... 95% 27.8M 0s
 37150K .......... .......... .......... .......... .......... 95% 51.0M 0s
 37200K .......... .......... .......... .......... .......... 95%  102M 0s
 37250K .......... .......... .......... .......... .......... 95% 61.5M 0s
 37300K .......... .......... .......... .......... .......... 95% 82.9M 0s
 37350K .......... .......... .......... .......... .......... 95% 82.5M 0s
 37400K .......... .......... .......... .......... .......... 95%  118M 0s
 37450K .......... .......... .......... .......... .......... 95% 70.1M 0s
 37500K .......... .......... .......... .......... .......... 96% 86.4M 0s
 37550K .......... .......... .......... .......... .......... 96% 83.4M 0s
 37600K .......... .......... .......... .......... .......... 96%  105M 0s
 37650K .......... .......... .......... .......... .......... 96%  108M 0s
 37700K .......... .......... .......... .......... .......... 96% 99.9M 0s
 37750K .......... .......... .......... .......... .......... 96%  104M 0s
 37800K .......... .......... .......... .......... .......... 96%  160M 0s
 37850K .......... .......... .......... .......... .......... 96% 97.1M 0s
 37900K .......... .......... .......... .......... .......... 97%  108M 0s
 37950K .......... .......... .......... .......... .......... 97% 91.0M 0s
 38000K .......... .......... .......... .......... .......... 97%  158M 0s
 38050K .......... .......... .......... .......... .......... 97%  109M 0s
 38100K .......... .......... .......... .......... .......... 97%  227M 0s
 38150K .......... .......... .......... .......... .......... 97%  105M 0s
 38200K .......... .......... .......... .......... .......... 97% 60.2M 0s
 38250K .......... .......... .......... .......... .......... 97% 93.8M 0s
 38300K .......... .......... .......... .......... .......... 98%  109M 0s
 38350K .......... .......... .......... .......... .......... 98%  101M 0s
 38400K .......... .......... .......... .......... .......... 98%  109M 0s
 38450K .......... .......... .......... .......... .......... 98%  291M 0s
 38500K .......... .......... .......... .......... .......... 98%  112M 0s
 38550K .......... .......... .......... .......... .......... 98% 13.3M 0s
 38600K .......... .......... .......... .......... .......... 98% 31.7M 0s
 38650K .......... .......... .......... .......... .......... 98% 29.9M 0s
 38700K .......... .......... .......... .......... .......... 99% 42.7M 0s
 38750K .......... .......... .......... .......... .......... 99% 65.0M 0s
 38800K .......... .......... .......... .......... .......... 99%  137M 0s
 38850K .......... .......... .......... .......... .......... 99% 76.9M 0s
 38900K .......... .......... .......... .......... .......... 99% 63.6M 0s
 38950K .......... .......... .......... .......... .......... 99%  103M 0s
 39000K .......... .......... .......... .......... .......... 99% 83.5M 0s
 39050K .......... .......... .......... .......... .......... 99%  159M 0s
 39100K ..                                                    100% 94.6M=0.6s

2019-04-01 16:04:40 (60.8 MB/s) - ‘/tmp/docker-ce_18.06.3~ce~3-0~ubuntu_amd64.deb’ saved [40040990/40040990]

sudo: Reading package lists...unable to resolve host ip-10-2-116-39

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libltdl7
Recommended packages:
  aufs-tools cgroupfs-mount | cgroup-lite pigz
The following NEW packages will be installed:
  docker-ce libltdl7
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 38.3 kB/40.1 MB of archives.
After this operation, 198 MB of additional disk space will be used.
Get:1 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial/main amd64 libltdl7 amd64 2.4.6-0.1 [38.3 kB]
Get:2 /tmp/docker-ce_18.06.3~ce~3-0~ubuntu_amd64.deb docker-ce amd64 18.06.3~ce~3-0~ubuntu [40.0 MB]
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 38.3 kB in 0s (62.4 kB/s)
Selecting previously unselected package libltdl7:amd64.

(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading
 database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading dat
abase ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading databas
e ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 51281 files and directories currently installed.)

Preparing to unpack .../libltdl7_2.4.6-0.1_amd64.deb ...

Unpacking libltdl7:amd64 (2.4.6-0.1) ...

Selecting previously unselected package docker-ce.

Preparing to unpack .../docker-ce_18.06.3~ce~3-0~ubuntu_amd64.deb ...

Unpacking docker-ce (18.06.3~ce~3-0~ubuntu) ...

Processing triggers for libc-bin (2.23-0ubuntu10) ...

Processing triggers for man-db (2.7.5-1) ...

Processing triggers for systemd (229-4ubuntu21.4) ...

Processing triggers for ureadahead (0.100.0-19) ...

Setting up libltdl7:amd64 (2.4.6-0.1) ...

Setting up docker-ce (18.06.3~ce~3-0~ubuntu) ...

Processing triggers for libc-bin (2.23-0ubuntu10) ...

Processing triggers for systemd (229-4ubuntu21.4) ...

Processing triggers for ureadahead (0.100.0-19) ...

sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
Synchronizing state of docker.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable docker
time="2019-04-01T19:04:49+03:00" level=info msg="[docker] - success"
time="2019-04-01T19:04:49+03:00" level=info msg="[certificates] - started"
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
Cluster "kubernetes" set.
User "kubernetes" set.
sudo: unable to resolve host ip-10-2-116-39
Context "kubernetes" created.
sudo: unable to resolve host ip-10-2-116-39
Switched to context "kubernetes".
sudo: unable to resolve host ip-10-2-116-39
Generating RSA private key, 2048 bit long modulus
...............................................................+++
...................................................................................+++
e is 65537 (0x10001)
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
Unable to connect to the server: EOF
sudo: unable to resolve host ip-10-2-116-39
error: unable to recognize "/etc/kubernetes/pki/request.yaml": Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com/api?timeout=32s: EOF
No resources found
sudo: unable to resolve host ip-10-2-116-39
Unable to connect to the server: EOF
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
time="2019-04-01T19:04:51+03:00" level=info msg="[certificates] - success"
time="2019-04-01T19:04:51+03:00" level=info msg="[kubeadm] - started"
sudo: unable to resolve host ip-10-2-116-39
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Hit:2 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security/main Sources [144 kB]
Get:5 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/restricted Sources [2,116 B]
Get:7 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial/main Sources [868 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [104 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/multiverse Sources [3,416 B]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [628 kB]
Get:11 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial/restricted Sources [4,808 B]
Get:12 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial/universe Sources [7,728 kB]
Get:13 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [259 kB]
Get:14 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [432 kB]
Get:15 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [174 kB]
Get:16 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [5,604 B]
Get:17 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [2,676 B]
Get:18 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial/multiverse Sources [179 kB]
Get:19 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [7,532 kB]
Get:20 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial/universe Translation-en [4,354 kB]
Get:21 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [144 kB]
Get:22 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial/multiverse Translation-en [106 kB]
Get:23 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main Sources [332 kB]
Get:24 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [2,536 B]
Get:25 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe Sources [254 kB]
Get:26 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse Sources [8,764 B]
Get:27 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [927 kB]
Get:28 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [373 kB]
Get:29 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [7,616 B]
Get:30 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/restricted Translation-en [2,272 B]
Get:31 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [743 kB]
Get:32 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [308 kB]
Get:33 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.7 kB]
Get:34 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8,440 B]
Get:35 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/main Sources [4,848 B]
Get:36 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe Sources [6,740 B]
Get:37 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [7,280 B]
Get:38 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [4,456 B]
Get:39 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [7,804 B]
Get:40 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [4,184 B]
Fetched 26.0 MB in 8s (3,237 kB/s)
Reading package lists...
sudo: unable to resolve host ip-10-2-116-39
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libcurl3-gnutls
The following packages will be upgraded:
  apt-transport-https curl libcurl3-gnutls
3 upgraded, 0 newly installed, 0 to remove and 115 not upgraded.
Need to get 350 kB of archives.
After this operation, 1,024 B of additional disk space will be used.
Get:1 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 curl amd64 7.47.0-1ubuntu2.12 [139 kB]
Get:2 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libcurl3-gnutls amd64 7.47.0-1ubuntu2.12 [185 kB]
Get:3 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 apt-transport-https amd64 1.2.31 [26.6 kB]
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 350 kB in 1s (332 kB/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading
 database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading dat
abase ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading databas
e ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 51506 files and directories currently installed.)

Preparing to unpack .../curl_7.47.0-1ubuntu2.12_amd64.deb ...

Unpacking curl (7.47.0-1ubuntu2.12) over (7.47.0-1ubuntu2.8) ...

Preparing to unpack .../libcurl3-gnutls_7.47.0-1ubuntu2.12_amd64.deb ...

Unpacking libcurl3-gnutls:amd64 (7.47.0-1ubuntu2.12) over (7.47.0-1ubuntu2.8) ...

Preparing to unpack .../apt-transport-https_1.2.31_amd64.deb ...

Unpacking apt-transport-https (1.2.31) over (1.2.27) ...

Processing triggers for man-db (2.7.5-1) ...

Processing triggers for libc-bin (2.23-0ubuntu10) ...

Setting up libcurl3-gnutls:amd64 (7.47.0-1ubuntu2.12) ...

Setting up curl (7.47.0-1ubuntu2.12) ...

Setting up apt-transport-https (1.2.31) ...

Processing triggers for libc-bin (2.23-0ubuntu10) ...

sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
OK
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:5 https://apt.kubernetes.io kubernetes-xenial InRelease [161 B]
Get:6 https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages [25.0 kB]
Fetched 34.0 kB in 3s (9,543 B/s)
Reading package lists...
sudo: unable to resolve host ip-10-2-116-39
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  conntrack cri-tools ebtables kubernetes-cni socat
The following NEW packages will be installed:
  conntrack cri-tools ebtables kubeadm kubectl kubelet kubernetes-cni socat
0 upgraded, 8 newly installed, 0 to remove and 115 not upgraded.
Need to get 46.6 MB of archives.
After this operation, 269 MB of additional disk space will be used.
Get:1 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial/main amd64 conntrack amd64 1:1.4.3-3 [27.3 kB]
Get:2 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 ebtables amd64 2.0.10.4-3.4ubuntu2.16.04.2 [79.9 kB]
Get:3 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu xenial/universe amd64 socat amd64 1.7.3.1-1 [321 kB]
Get:4 https://apt.kubernetes.io kubernetes-xenial/main amd64 cri-tools amd64 1.12.0-00 [5,343 kB]
Get:5 https://apt.kubernetes.io kubernetes-xenial/main amd64 kubernetes-cni amd64 0.7.5-00 [6,473 kB]
Get:6 https://apt.kubernetes.io kubernetes-xenial/main amd64 kubelet amd64 1.13.5-00 [19.1 MB]
Get:7 https://apt.kubernetes.io kubernetes-xenial/main amd64 kubectl amd64 1.13.5-00 [7,852 kB]
Get:8 https://apt.kubernetes.io kubernetes-xenial/main amd64 kubeadm amd64 1.13.5-00 [7,363 kB]
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 46.6 MB in 7s (6,637 kB/s)
Selecting previously unselected package conntrack.

(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading
 database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading dat
abase ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading databas
e ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 51506 files and directories currently installed.)

Preparing to unpack .../conntrack_1%3a1.4.3-3_amd64.deb ...

Unpacking conntrack (1:1.4.3-3) ...

Selecting previously unselected package cri-tools.

Preparing to unpack .../cri-tools_1.12.0-00_amd64.deb ...

Unpacking cri-tools (1.12.0-00) ...

Selecting previously unselected package ebtables.

Preparing to unpack .../ebtables_2.0.10.4-3.4ubuntu2.16.04.2_amd64.deb ...

Unpacking ebtables (2.0.10.4-3.4ubuntu2.16.04.2) ...

Selecting previously unselected package kubernetes-cni.

Preparing to unpack .../kubernetes-cni_0.7.5-00_amd64.deb ...

Unpacking kubernetes-cni (0.7.5-00) ...

Selecting previously unselected package socat.

Preparing to unpack .../socat_1.7.3.1-1_amd64.deb ...

Unpacking socat (1.7.3.1-1) ...

Selecting previously unselected package kubelet.

Preparing to unpack .../kubelet_1.13.5-00_amd64.deb ...

Unpacking kubelet (1.13.5-00) ...

Selecting previously unselected package kubectl.

Preparing to unpack .../kubectl_1.13.5-00_amd64.deb ...

Unpacking kubectl (1.13.5-00) ...

Selecting previously unselected package kubeadm.

Preparing to unpack .../kubeadm_1.13.5-00_amd64.deb ...

Unpacking kubeadm (1.13.5-00) ...

Processing triggers for man-db (2.7.5-1) ...

Processing triggers for systemd (229-4ubuntu21.4) ...

Processing triggers for ureadahead (0.100.0-19) ...

Setting up conntrack (1:1.4.3-3) ...

Setting up cri-tools (1.12.0-00) ...

Setting up ebtables (2.0.10.4-3.4ubuntu2.16.04.2) ...

update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults

Setting up kubernetes-cni (0.7.5-00) ...

Setting up socat (1.7.3.1-1) ...

Setting up kubelet (1.13.5-00) ...

Setting up kubectl (1.13.5-00) ...

Setting up kubeadm (1.13.5-00) ...

Processing triggers for systemd (229-4ubuntu21.4) ...

Processing triggers for ureadahead (0.100.0-19) ...

sudo: unable to resolve host ip-10-2-116-39
kubelet set on hold.
kubeadm set on hold.
kubectl set on hold.
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
[preflight] Running pre-flight checks
	[WARNING Hostname]: hostname "ip-10-2-116-39" could not be reached
	[WARNING Hostname]: hostname "ip-10-2-116-39": lookup ip-10-2-116-39 on 10.2.0.2:53: no such host
[discovery] Trying to connect to API Server "internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443"
[discovery] Created cluster-info discovery client, requesting info from "https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443"
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Failed to request cluster info, will try again: [Get https://internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443/api/v1/namespaces/kube-
public/configmaps/cluster-info: EOF]
[discovery] Cluster info signature and contents are valid and no TLS pinning was specified, will use API Server "internal-in-68e300a4-468363844.ap-south-1.elb.a
mazonaws.com:443"
[discovery] Successfully established connection with API Server "internal-in-68e300a4-468363844.ap-south-1.elb.amazonaws.com:443"
[join] Reading configuration from the cluster...
[join] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet] Downloading configuration for the kubelet from the "kubelet-config-1.13" ConfigMap in the kube-system namespace
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Activating the kubelet service
[tlsbootstrap] Waiting for the kubelet to perform the TLS Bootstrap...
[patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "ip-10-2-116-39" as an annotation

This node has joined the cluster:
* Certificate signing request was sent to apiserver and a response was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the master to see this node join the cluster.

time="2019-04-01T19:08:15+03:00" level=info msg="[kubeadm] - success"
time="2019-04-01T19:08:15+03:00" level=info msg="[kubelet] - started"
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
time="2019-04-01T19:08:17+03:00" level=info msg="[kubelet] - success"
time="2019-04-01T19:08:17+03:00" level=info msg="[poststart] - started"
PostStart started
sudo: unable to resolve host ip-10-2-116-39
sudo: unable to resolve host ip-10-2-116-39
PostStart finished
time="2019-04-01T19:08:18+03:00" level=info msg="[poststart] - success"
</details>

### PR DESCRIPTION
**Pull request by stgleb**
Use private IP instead of domain names for provisioning
to avoid incosistencies with domain dns records.

Closes #1349

### CODE REVIEW

File: pkg/provisioner/provisioner.go [hunk 1]
```diff
@@ -420,7 +432,7 @@ func (tp *TaskProvisioner) provisionNodes(ctx context.Context, profile *profile.
 
 		if err != nil {
 			logrus.Errorf("Error getting writer for %s", fileName)
-			return
+			return errors.Wrapf(err, "Error getting writer for %s", fileName)
```
Comment (saheienko) [inline pkg/provisioner/provisioner.go]: No need to log this error a few times.
