### PR TITLE
Fix DNS for kubelet

### LINKED ISSUE #1292: DNS doesn't work
**Short Summary:**
DNS doesn't work.

**Steps to Reproduce:**
1. Deploy cluster using master branch.
2. try to resolve dns name of any service from pod within the same namespace.

**Expected Results:**
dns name is resolved to ip address

**Actual Results:**
dns name is NOT resolved to ip address

**Dev Info:** (add links to log files)
1. Output of `go version`: 
```go version go1.11.1 linux/amd64```
2. Commit hash or release tag used (`git log`):
```commit 846d67d2355fde12c5bfa66d8fd9aee94a7b4b39 (HEAD -> master, upstream/master)
Author: Gleb <glebstepanov1992@gmail.com>
Date:   Tue Feb 12 17:44:02 2019 +0200

    Update docker (#1287)
```
3. Number of Masters and Nodes:
```1 msater 3 nodes```
4. Cloud Provider:
AWS
5. Logs from `/tasks/{task_id}/logs/ws` UI/API endpoint for involved clusters:

6. Log files from `/tmp`, on the machine Control is running on (for example: `/tmp/314c2c2c-62b7-461b-8022-04dabeb0d19d.log`):

### PR DESCRIPTION
**Pull request by stgleb**
Store DNS IP inside kube model and set DNS IP to
each kubelet

Closes #1292

### CODE REVIEW

File: pkg/model/kube.go [hunk 1]
```diff
@@ -26,6 +26,7 @@ type Kube struct {
 	Region       string      `json:"region"`
 	Zone         string      `json:"zone" valid:"-"`
 	ServicesCIDR string      `json:"servicesCIDR"`
+	DNSIP        string      `json:"dnsip"`
```
Comment (saheienko) [inline pkg/model/kube.go]: Could you format this with the (gomodifytags)[https://github.com/fatih/gomodifytags] tool?

Comment (stgleb) [reply pkg/model/kube.go]: done
